language: minimal

branches:
  only:
    - master

git:
  submodules: false

services:
  - docker

install:
  - sudo apt-get install -y awscli

before_script:
  - make ecr-login

script:
  - make docker
